version: '3.7'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=lotto
      - POSTGRES_USER=lotto
      - POSTGRES_PASSWORD=lotto
    ports:
      - '5431:5432'
  localstack:
    image: localstack/localstack:0.12.12
    ports:
      - 4566:4566
    environment:
      - SERVICES=s3,lambda,serverless,sqs
      - AWS_DEFAULT_REGION=eu-central-1
      - EDGE_PORT=4566
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_DOCKER_NETWORK=application_default
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - "${PWD}/ls_tmp:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  app:
    image: appdev2:Dockerfile
    ports:
      - 80:8080
    environment:
      - DB_HOST=postgres
